sculpin:
    output_dir: public_%kernel.environment%
    exclude:
        - _sass/**
sculpin_content_types:
    projects:
        type: path
        enabled: true
        permalink: :basename/index.html
